% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Nov-2024 03:44:13
%  MATLAB version: 23.2.0.2485118 (R2023b) Update 6
% -------------------------------------------------------------------
saveVarsMat = load('RPratical.mat');

Auto_theft = saveVarsMat.Auto_theft; % <1x1 table> unsupported class

clear saveVarsMat;
